### PR TITLE
fix: kvstore improvements (address param, transfer method)

### PR DESCRIPTION
**Pull request by stanleyjones**
## Description

Previously:
```ts
export interface KVStorePutParam {
  key: string
  value: any
  owner?: Address
}
```

But we send addresses in their string format. Consider `to` and `from` in `ledger.send`:
```ts
export type LedgerSendParam = {
  from?: string
  to: string
  amount: bigint
  symbol: string
}
```

## Related Issue

Unblocks https://github.com/liftedinit/roadmap/issues/19

## Testing

Tests pass.

## Breaking Changes (if applicable)

None.

## Checklist:

- [x] I have read and followed the CONTRIBUTING guidelines for this project.
- [x] I have added or updated tests and they pass.
- [x] I have added or updated documentation and it is accurate.
- [x] I have noted any breaking changes in this module or downstream modules.

### CODE REVIEW

**Review by hansl — COMMENTED** [review]
Address should work too. Why not `Address | string`?

**Comment by stanleyjones** [comment]
I can do that for now. Eventually I'd like to get rid of the Address type though: https://github.com/liftedinit/many-js/pull/91

**Comment by stanleyjones** [comment]
Putting back in WIP while I add `transfer` since that's needed for immutability.

**Comment by stanleyjones** [comment]
Ready for review again. Added `kvstore.transfer` and made stuff `string | Address`.

**Pull request merged**
