### PR TITLE
Circleci

### PR DESCRIPTION
**Pull request by tantommy**
## Description

- adds circleci config
- adds .nvmrc set to node 16
- adds "files" property in package.json to limit files to `dist` and `README`
- publish to NPM and Github when tag is pushed

## Related Issue

Fixes https://github.com/liftedinit/many-js/issues/64
Fixes https://github.com/liftedinit/many-js/issues/67

### CODE REVIEW

**Review by fmorency — COMMENTED** [review]
Basically the same comments as on `albert`: check if you can use the utility functions from the `node` orb.

https://circleci.com/developer/orbs/orb/circleci/node#quick-start

I would also pin the node version(s) you're testing on.

**Review by hansl — APPROVED** [review]
LGTM, should wait for @fmorency approval before merging.

**Review by fmorency — APPROVED** [review]
nit: add `resource_class`: https://circleci.com/docs/configuration-reference#resourceclass

I won't block the merge if you want to do it later but it's good practice to not rely on the default resource class since they change in time.

**Comment by tantommy** [comment]
> https://circleci.com/docs/configuration-reference#resourceclass

resource class has been added.

**Comment by tantommy** [comment]
> nit: add `resource_class`: https://circleci.com/docs/configuration-reference#resourceclass
> 
> I won't block the merge if you want to do it later but it's good practice to not rely on the default resource class since they change in time.

done. resource class has been added.

**Pull request merged**
