### PR TITLE
Blockchain

### PR DESCRIPTION
**Pull request by tantommy**
## Description

- adds blockchain API's
  - info
  - block
  - list
  - transaction
  - request
  - response

## Testing

- jest tests added

## Related Issues
Fixes https://github.com/liftedinit/many-js/issues/72

### CODE REVIEW

**Comment by tantommy** [comment]
merge https://github.com/liftedinit/many-js/pull/70 first

**Comment by tantommy** [comment]
let block explorer test out this branch first.  After everything works as expected, we'll merge this in.

**Review by mjsorribas — APPROVED** [review]

**Comment by hansl** [comment]
@stanleyjones do we want this somehow in? I'm removing myself from the reviewer list, but I'll let you close if you think it's not needed.

**Comment by stanleyjones** [comment]
Closing in favor of #90

**Pull request closed without merging**
